"""empty message

Revision ID: 4d7a02cc2076
Revises: 7fea7427e9d6
Create Date: 2019-10-31 14:32:55.453545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7a02cc2076'
down_revision = '7fea7427e9d6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('brief', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('bounty', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ccr_liker',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ccr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccr_id'], ['ccr.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('proposal', sa.Column('ccr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposal', 'ccr', ['ccr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'ccr_id')
    op.drop_table('ccr_liker')
    op.drop_table('ccr')
    # ### end Alembic commands ###
