"""empty message

Revision ID: 4f1f80030390
Revises: e3339020e697
Create Date: 2019-11-26 22:04:49.420851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1f80030390'
down_revision = 'e3339020e697'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfp', sa.Column('ccr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rfp', 'ccr', ['ccr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfp', type_='foreignkey')
    op.drop_column('rfp', 'ccr_id')
    # ### end Alembic commands ###
