"""empty message

Revision ID: 7b8873f5bd56
Revises: 9d2f7db5b5a6
Create Date: 2019-11-18 14:05:45.565684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8873f5bd56'
down_revision = '9d2f7db5b5a6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('brief', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('proposal_contribution', sa.Column('ccr_id', sa.Integer(), nullable=True))
    op.alter_column('proposal_contribution', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'proposal_contribution', 'ccr', ['ccr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal_contribution', type_='foreignkey')
    op.alter_column('proposal_contribution', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('proposal_contribution', 'ccr_id')
    op.drop_table('ccr')
    # ### end Alembic commands ###
